spring:
  rabbitmq:
    host: 192.168.88.100
    port: 5672
    username: admin
    password: 123
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true